### ISSUE TITLE
在yml文件配置hikari属性后台读取不到

### ISSUE THREAD

**Issue by bandiandian** [xujijun/my-spring-boot#2]
我在yml里配置
![image](https://cloud.githubusercontent.com/assets/2092680/22818058/1020fbd2-efa6-11e6-81bb-c1b7796bc042.png)
但是debug后台启动的时候，还是取的默认值
![image](https://cloud.githubusercontent.com/assets/2092680/22818091/3930437a-efa6-11e6-9d2c-10c797a11144.png)

**Comment by xujijun** [comment]
我的好像没问题哦：
![image](https://cloud.githubusercontent.com/assets/5730332/24141094/509b7a90-0e5d-11e7-9a61-fe9e5c86d64e.png)
你的配置文件能截全些来看看吗？

**Comment by bandiandian** [comment]
嗯 现在好使了，谢谢了~
