### ISSUE TITLE
没看到数据库

### ISSUE THREAD

**Issue by zoclee2015** [xujijun/my-spring-boot#5]
能传递一份数据结构吗，在工程里没看到

**Comment by xujijun** [comment]
CREATE TABLE `t_person` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `first_name` varchar(6) DEFAULT NULL,
  `last_name` varchar(2) DEFAULT NULL,
  `birth_date` date DEFAULT NULL,
  `sex` varchar(1) DEFAULT NULL,
  `phone_no` varchar(11) DEFAULT NULL,
  `update_dt` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4;
